//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWizard.Locale.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgileWizard.Locale.Resources.Views.AccountString", typeof(AccountString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帐号信息.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新用户.
        /// </summary>
        public static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录出错了：.
        /// </summary>
        public static string LoginFailedAndTryAgain {
            get {
                return ResourceManager.GetString("LoginFailedAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string LogOnButtonText {
            get {
                return ResourceManager.GetString("LogOnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string LogOnTitle {
            get {
                return ResourceManager.GetString("LogOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码达不到要求。请确保密码长度大于或等于6位！.
        /// </summary>
        public static string NotMatchPasswordRule {
            get {
                return ResourceManager.GetString("NotMatchPasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名及密码。.
        /// </summary>
        public static string PleaseEnterUserNameAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果还没有帐号，请点击这里.
        /// </summary>
        public static string RegisterPleaseClick {
            get {
                return ResourceManager.GetString("RegisterPleaseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该用户已存在.
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不能为空.
        /// </summary>
        public static string UserNameCanNotBeNull {
            get {
                return ResourceManager.GetString("UserNameCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名或密码错误.
        /// </summary>
        public static string UserOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("UserOrPasswordIsIncorrect", resourceCulture);
            }
        }
    }
}
