require  "albacore"
require 'fileutils'

if not((defined? ROOT)) then
	load File.join(File.dirname(__FILE__), 'varConfig.rb')
end


desc "Build the agile wizard teamcity file"
msbuild :compile, :mode do |msb, args|
	args.with_defaults(:mode =>  COMILE_MODE)
	
	msb.solution = SOLUTION
	msb.verbosity = "minimal"
	msb.targets :clean, :build
	msb.parameters  ["/P:Configuration=" + args[:mode]]
end

task :test=>[:buildDeploymentPackage,
			:deployLocal,
			:modifyTestProjectStartSiteConfig,
			:openIE,
            :xunit
			] do    
end

desc 'starting to build deployment package for the website project'
msbuild :buildDeploymentPackage do |msb|
  puts "building deployment package"
    
  msb.solution = WEBSITE_PROJ
  msb.verbosity = "Quiet"
  msb.targets :publish
  msb.parameters  [ "/T:Package",
					"/P:Configuration=" + COMILE_MODE]
end

task :deployLocal do
	deploy_script_path = File.join(DEPLOY_SOURCE, "AgileWizard.Website.deploy.cmd")
	system("'"+ deploy_script_path + "'" + " /Y")
end

task :modifyTestProjectStartSiteConfig do
	require 'rexml/document'
	include REXML
	
	puts 'Changing the AT StartSite to http://localhost/'
	config_doc = Document.new(File.new(AT_CONFIG_PATH))
	config_doc.root.elements["appSettings//add[@key='WebsiteUrl']"].attributes['value'] = AT_CONFIG_SITE
	File.open(AT_CONFIG_PATH, 'w'){|f| f.write config_doc.to_s}
end

task :openIE do
	puts "start one IE for forbidding the COM error when WatiN running"
	system("start iexplore.exe about:blank")
end

xunit :xunit =>[:openIE] do |xunit|
    xunit.command = XUNIT_PATH
	xunit.assemblies = [
		File.join(OUTPUT_DLL_DIR, "AgileWizard.Domain.Tests.dll"),
		File.join(OUTPUT_DLL_DIR, "AgileWizard.Website.Tests.dll"),
		File.join(OUTPUT_DLL_DIR, "AgileWizard.AcceptanceTests.dll"),
		File.join(OUTPUT_DLL_DIR, "AgileWizard.IntegrationTests.dll"),
		File.join(OUTPUT_DLL_DIR, "AgileWizard.Locale.Tests.dll")
		]
end

desc "finialize the whole step"
task :clean => :closeIE do

end

task :closeIE do
	puts "close all IE when finish the process"
	system("call taskkill /F /IM iexplore*")
end

desc 'Currently this task is useless'
task :startWebServer do
  START_COMMAND= "\"" + WEB_DEV_FULL_NAME + "\"" + " /port:"  + WEB_PORT + " /path:\"" + WEBSITE_LOCATION+"\""
  
  puts START_COMMAND
  system("call taskkill /F /IM " + WEB_DEV_NAME)

  Thread.new{system(START_COMMAND)}
  sleep(1)
end

task :startServer => [:compile, :startWebServer, :openUrl]

task :openUrl do
	LAUNCH_URL = "http://localhost:"+WEB_PORT
	system("start iexplore.exe " + LAUNCH_URL)
end


desc 'starting to publish the website project'
msbuild :publish do |msb|
	msb.solution = WEBSITE_PROJ
	msb.verbosity = "minimal"
	msb.targets :publish
	msb.parameters  [ "/T:Package",
						"/P:Configuration=" + COMILE_MODE]
end


desc "initialize the server environment"
task :deleteBin do
  puts "delete the bin directory before building"
  if FileTest::directory?(OUTPUT_DLL_DIR) then
		FileUtils.rm_rf OUTPUT_DLL_DIR
	end
end

task :teamcity => [:deleteBin, :compile,:test,:clean]