// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.4.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace AgileWizard.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AddResourceFeature : Xunit.IUseFixture<AddResourceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddResource.feature"
#line hidden
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Add Resource", "As a admin,\r\nI should be able to record the title, content and author", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public virtual void SetFixture(AddResourceFeature.FixtureData fixtureData)
        {
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        public virtual void AddResource(string title, string author, string tags, string referenceurl, string content)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("add resource", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("new resource with  title - {0} and content - {1} and author - {2} and tags - {3} " +
                        "and reference url - {4}", title, content, author, tags, referenceurl));
#line 7
 testRunner.When("submit resource to system");
#line 8
 testRunner.Then("navigate to details page");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add Resource")]
        [Xunit.TraitAttribute("Description", "add resource")]
        public virtual void AddResource_SimpleResource()
        {
            this.AddResource("simple Resource", "Test Author", "Agilewizard,Shanghai", "http://www.cnblogs.com/tengzy/", "simple Content");
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add Resource")]
        [Xunit.TraitAttribute("Description", "add resource")]
        public virtual void AddResource_EmbedVideoResource()
        {
            this.AddResource("embed video Resource", "Test Author", "Agilewizard,Shanghai", "http://www.cnblogs.com/tengzy/", "@\"<embed src=\"\"http://player.youku.com/player.php/sid/XMjI2MjI2MTQw/v.swf\"\" quali" +
                    "ty=\"\"high\"\" width=\"\"480\"\" height=\"\"400\"\" align=\"\"middle\"\" allowScriptAccess=\"\"sa" +
                    "meDomain\"\" type=\"\"application/x-shockwave-flash\"\"></embed>\"");
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AddResourceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AddResourceFeature.FeatureTearDown();
            }
        }
    }
}
#endregion
