// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.4.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace AgileWizard.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EditResourceFeature : Xunit.IUseFixture<EditResourceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EditResource.feature"
#line hidden
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Edit resource", "As a admin,\r\nI can edit title, content, tag of a resource", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public virtual void SetFixture(EditResourceFeature.FixtureData fixtureData)
        {
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Edit resource")]
        [Xunit.TraitAttribute("Description", "Open a resource to edit")]
        public virtual void OpenAResourceToEdit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Open a resource to edit", new string[] {
                        "Ignore"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Title",
                        "Resource Title"});
            table1.AddRow(new string[] {
                        "Content",
                        "Resource Content"});
            table1.AddRow(new string[] {
                        "Author",
                        "Jackon Zhang"});
            table1.AddRow(new string[] {
                        "ReferenceUrl",
                        "http://www.neodream.info/blog"});
            table1.AddRow(new string[] {
                        "Tags",
                        "Test,Integration"});
#line 7
 testRunner.Given("there is a resource", ((string)(null)), table1);
#line 14
 testRunner.When("open the resource to edit");
#line 15
 testRunner.Then("navigate to edit page");
#line 16
 testRunner.And("show edit for the title, content, author and tags");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Xunit.FactAttribute(Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Edit resource")]
        [Xunit.TraitAttribute("Description", "Edit a resource")]
        public virtual void EditAResource()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit a resource", new string[] {
                        "Ignore"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Title",
                        "Resource Title"});
            table2.AddRow(new string[] {
                        "Content",
                        "Resource Content"});
            table2.AddRow(new string[] {
                        "Author",
                        "Jackon Zhang"});
            table2.AddRow(new string[] {
                        "ReferenceUrl",
                        "http://www.neodream.info/blog"});
            table2.AddRow(new string[] {
                        "Tags",
                        "Test,Integration"});
#line 20
 testRunner.Given("there is a resource", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Title",
                        "Modified Resource Title"});
            table3.AddRow(new string[] {
                        "Content",
                        "Modified Resource Content"});
            table3.AddRow(new string[] {
                        "Author",
                        "Ron Jeffries"});
            table3.AddRow(new string[] {
                        "ReferenceUrl",
                        "http://xprogramming.com"});
            table3.AddRow(new string[] {
                        "Tags",
                        "Test,Integration,XP"});
#line 27
 testRunner.When("modify the resource", ((string)(null)), table3);
#line 34
 testRunner.Then("navigate to details page");
#line 35
 testRunner.And("display the title, content, author and submit user and tags");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                EditResourceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                EditResourceFeature.FeatureTearDown();
            }
        }
    }
}
#endregion
